//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Quantity
    {
        public string WH_Name { get; set; }
        public int P_code { get; set; }
        public Nullable<int> S_id { get; set; }
        public int quantity { get; set; }
        public int Per_id_S { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supply_Permission Supply_Permission { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
